CORES_PER_NODE = 8
FAT_NAME = mem72GB

# How to produce sbatch files from m4 files
SBATCH_M4_COMMON_DEFINITIONS =-D__PROJECT__=$(PROJECT) -D__EMAIL__=$(EMAIL) -D__PREFIX__=$(PREFIX) -D__CORES_PER_NODE__=$(CORES_PER_NODE)
SBATCH_M4_STANDARD_CALL = m4 $(SBATCH_M4_COMMON_DEFINITIONS) $< > $@
SBATCH_M4_SINGLE_MAKE_TARGET_NODE_CALL = m4 $(SBATCH_M4_COMMON_DEFINITIONS) -D__MAKE_TARGET__=$(basename $@) -D__N_NODES__=$(DENOISE_N_NODES) -D__PARTITION__=node $< > $@
SBATCH_M4_SINGLE_MAKE_TARGET_SINGLE_NODE_CALL_FAT = m4 $(SBATCH_M4_COMMON_DEFINITIONS) -D__MAKE_TARGET__=$(basename $@) -D__N_NODES__=1 -D__PARTITION__=node -D__EXTRA_SBATCH_OPT__="SBATCH -C $(FAT_NAME)" $< > $@
SBATCH_M4_SINGLE_MAKE_TARGET_CORE_CALL = m4 $(SBATCH_M4_COMMON_DEFINITIONS) -D__MAKE_TARGET__=$(basename $@) -D__N_NODES__=1 -D__PARTITION__=core $< > $@
